version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    restart: on-failure
    ports:
      - 8080:8080
    platform: linux/x86_64
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./backend
    restart: on-failure
    ports:
      - 3001:3001
    platform: linux/x86_64
    depends_on:
      db:
        condition: service_healthy
    environment:
      - JWT_SECRET=senha*super*secreta
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=users-db
      - MYSQL_HOST=db
      - MYSQL_USER=root
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5